name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@7d2b570c76b71c7dc980fe1038eaba179dba3bc9 # 0.5.0
    with:
      artifact-name: ${{ needs.assets.outputs.phar-artifact-name }}
