name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@ff8c9e97097417990bfd5286471e009bb00636d2 # 0.3.2
    with:
      artifact-name: ${{ needs.assets.outputs.phar-artifact-name }}
