name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: 'Create release'
    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@b205b470c2f8b2eec7ca41caedf3c401abda2dcf # 0.7.1
